aeternity/mdw-frontend

nuxt.config.js, store/generations.js, store/index.js
=> Fix work of websockets

pages/contracts/index.vue, pages/generations/index.vue, pages/names/index.vue, pages/oracles/index.vue, pages/transactions/index.vue, store/generations.js, store/index.js, store/transactions.js
=> Make SSR work correctly on every page

Dockerfile, nuxt.config.js, package-lock.json, package.json, pages/auctions.vue, pages/transactions/_transaction/index.vue, partials/name.vue, partials/nameAuction.vue, plugins/directives/vueSliderComponent.js, store/names.js, store/transactions.js, styles/index.scss
=> Fix names/auctions related issues

pages/generations/_generation/index.vue, pages/transactions/_transaction/index.vue
fixes #31,
fixes appealing to modals state,
removes pointless requests to the mdw
=> Refactoring

partials/txListItem.vue, partials/txListType/oracleRespondTx.vue
part of #1 
https://github.com/aeternity/aeternity/blob/master/apps/aetx/src/aetx.erl#L585
=> Fix showing oracle_response_tx

partials/appHeader.vue
| After | Before | Before on too small screen |
|---|---|---|
| ![Screenshot 2021-03-12 at 17 43 27](https://user-images.githubusercontent.com/9007851/110955439-a98fc900-835a-11eb-907c-8370626d1cf9.png) | ![Screenshot 2021-03-12 at 17 43 17](https://user-images.githubusercontent.com/9007851/110955432-a694d880-835a-11eb-8571-a2db00d10ea2.png) | ![Screenshot 2021-03-12 at 17 46 53](https://user-images.githubusercontent.com/9007851/110955736-f378af00-835a-11eb-82a9-6db04081120d.png) |
=> appHeader: Fix rendering on tall screens

pages/contracts/index.vue, pages/generations/index.vue, pages/index.vue, pages/names/index.vue, pages/oracles/index.vue, pages/transactions/index.vue, store/contracts.js, store/generations.js, store/index.js, store/names.js, store/oracles.js, store/transactions.js, store/utils.js
fixes #32,
fixes problem with duplicate names
=> Use next page url from the middleware response to load additional data

.gitignore, pages/contracts/_transactions/_id.vue, pages/transactions/_transaction/index.vue, store/account.js
Adding more context on waiting for syncing. Someone who knows Vue could implement an automatic page reload maybe ?
=> add more meaningful error messages to "not found" contexts

README.md, nuxt.config.js, partials/appMainNav.vue, partials/transactionDetails.vue, partials/txListType/contractCallTx.vue, partials/txListType/gaAttachTx.vue, plugins/filters/decodeBase64.js, store/index.js
Fixes #8 
Fixes #54 
Fixes #77
=> Fix transaction data display

pages/transactions/_transaction/index.vue, partials/transactionDetails.vue, partials/txListItem.vue, partials/txListType/contractCallTx.vue, store/tokens.js
=> Add aex9 token transfer visualisation

pages/account/_transactions/_id.vue, pages/transactions/index.vue, partials/txListItem.vue, partials/txListType/aex9ReceivedTx.vue, partials/txListType/aex9SentTx.vue, partials/txListType/contractCallTx.vue, plugins/filters/formatToken.js, store/index.js, store/tokens.js
Fixes #80 
Token transactions are shown on account page
Added AEX9 transactions filters
=> Show token transfers on account page

pages/names/_search/index.vue
=> Display name auctions through search

components/loadMoreButton.vue, pages/account/_transactions/_id.vue, pages/auctions.vue, pages/contracts/_transactions/_id.vue, pages/contracts/index.vue, pages/generations/index.vue, pages/names/index.vue, pages/oracles/_queries/_id.vue, pages/oracles/index.vue, pages/transactions/index.vue, store/contracts.js, store/names.js, store/transactions.js
Fixes #94 
Pretty simple visual indication and preventing clicking while the call is being executed.
Fixes #85
=> "Load more" button loading indicator

pages/account/_transactions/_id.vue, pages/transactions/index.vue
Fixes #107 
Queries should also work on account transactions page
=> feat: handle filters through queries

plugins/filters/prefixedAmount.js
=> feat: adjust AE prefixed amount

pages/tokens/_token/index.vue, pages/tokens/index.vue, pages/transactions/_transaction/index.vue, partials/accountDetails.vue, partials/appMainNav.vue, partials/token.vue, plugins/filters/formatToken.js, store/tokens.js
=> feat: tokens dedicated page

pages/tokens/index.vue
=> feat: tokens page search query

pages/transactions/_transaction/index.vue, partials/functionCalls.vue, store/transactions.js
Fixes #113 
What else as information is needed to be displayed?
=> feat(transactions): display internal function calls

pages/account/_id.vue, pages/generations/_generation/index.vue, pages/transactions/index.vue, partials/internalTransfers.vue, partials/txListItem.vue, partials/txListType/internalTx.vue, store/index.js, store/transactions.js
Fixes #111 
On generation page
On account page
=> feat: display internal transfers

pages/tokens/_token/index.vue
=> fix: token view load more filter data #158

pages/account/_id.vue, pages/transactions/_transaction/index.vue, store/tokens.js
Added sub filter to filter contract_call transaction on account page
=> Feat: filter transactions based on AEX-9 and DEX for account
